services:
  librarium-init:
    image: ${LIBRARIUM_INIT_IMAGE:-ghcr.io/hem-labs/hex-librarium-init:latest}
    environment:
      HEX_LIBRARIUM: /hex/librarium
    volumes:
      - hex-librarium:/hex/librarium
    restart: "no"

  librarium-syncthing:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: ${LIBRARIUM_SYNCTHING_IMAGE:-ghcr.io/hem-labs/hex-librarium-syncthing:latest}
    container_name: hex-librarium-syncthing
    hostname: hex-librarium-syncthing
    depends_on:
      librarium-init:
        condition: service_completed_successfully
    environment:
      PUID: ${SYNCTHING_PUID:-0}
      PGID: ${SYNCTHING_PGID:-0}
      TZ: ${TZ:-Etc/UTC}
      HEX_LIBRARIUM: /hex/librarium
      SYNCTHING_DEVICE_NAME: ${SYNCTHING_DEVICE_NAME:-hex-librarium-syncthing}
      SYNCTHING_LISTEN_PORT: ${SYNCTHING_LISTEN_PORT:-22300}
    volumes:
      - hex-librarium:/hex/librarium
      - ${SYNCTHING_CONFIG_SOURCE:-./syncthing-config}:/config
    ports:
      - "${SYNCTHING_GUI_PORT:-18384}:8384/tcp"
      - "${SYNCTHING_LISTEN_PORT:-22300}:${SYNCTHING_LISTEN_PORT:-22300}/tcp"
      - "${SYNCTHING_LISTEN_PORT:-22300}:${SYNCTHING_LISTEN_PORT:-22300}/udp"
    # noinspection ComposeUnknownValues
    restart: ${SYNCTHING_RESTART:-no}

volumes:
  hex-librarium:
    name: hex-librarium
    external: true
